
version: 2

models:
  - name: exploded_demo_data
    description: "demographic table exploted with main metrics as columns"
  - name: lead_from_answers_parsed
    description: "Table on lead granurality, each column is one question on the form and it contains the answer the lead has given, for multiple answers questions there is one boolean column for each possible response"
  - name: all_metrics
    description: "table with all available metrics, from lead, form submission and demographics"
  - name: answer_codes
    description: "Form codes and their meaning"
  - name: answers_decoded
    description: "Gets the form responses table and adds a column with the answer in a more undarstendable format, each row is one answer given by one lead on a specific question"
    columns:
    - name: LEAD_ID
      description: "the id of the lead who has anwered that specific question"
    - name: QUESTION_KEY
      description: "Name of the question answered"
    - name: ANSWER_CODE
      description: "Answer given by the lead on that specific question, on a code format"
    - name: uncoded_answer
      description: "Uncoded answer, if there is a lack of information on the coding, it will keep coded"

sources:
  - name: homeBuddy
    database: personal-use-376010  
    schema: HomeBuddy  
    tables:
      - name: demographics
      - name: form_answers
      - name: leads
